name: C++ CI

on:
  push:
    branches: [ "main", "sem3.2" ]
  pull_request:
    branches: [ "main", "sem3.2" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y g++

    - name: Compile main program
      run: |
        g++ -o matrix_multiplier main.cpp -std=c++11
        echo "✅ Основная программа успешно скомпилирована"

    - name: Compile test program
      run: |
        g++ -o test_program test.cpp -std=c++11
        echo "✅ Тестовая программа успешно скомпилирована"

    - name: Run tests
      run: |
        echo "🧪 Запуск тестов..."
        ./test_program
        if [ $? -eq 0 ]; then
          echo "✅ Все тесты прошли успешно"
        else
          echo "❌ Некоторые тесты не прошли"
          exit 1
        fi

    - name: Test main program with sample input
      run: |
        echo "🔧 Тестирование основной программы с примером ввода..."
        # Создаем входные данные для тестирования
        echo -e "2\n2\n1\n2\n3\n4\n5\n6\n7\n8" > test_input.txt
        ./matrix_multiplier < test_input.txt > output.txt
        echo "✅ Основная программа выполнена успешно"

        # Проверяем ожидаемый вывод
        echo "Проверка вывода программы..."
        if grep -q "5 12" output.txt && grep -q "21 32" output.txt; then
          echo "✅ Вывод программы корректен"
        else
          echo "❌ Неправильный вывод программы"
          echo "Содержимое output.txt:"
          cat output.txt
          exit 1
        fi

    - name: Test memory management with valgrind
      run: |
        echo "🧠 Проверка управления памятью с помощью valgrind..."
        sudo apt-get install -y valgrind
        # Тестируем основную программу
        echo -e "2\n2\n1\n2\n3\n4\n5\n6\n7\n8" > test_input.txt
        valgrind --leak-check=full --error-exitcode=1 ./matrix_multiplier < test_input.txt
        if [ $? -eq 0 ]; then
          echo "✅ Утечек памяти не обнаружено"
        else
          echo "❌ Обнаружены утечки памяти"
          exit 1
        fi

        # Тестируем тестовую программу
        valgrind --leak-check=full --error-exitcode=1 ./test_program
        if [ $? -eq 0 ]; then
          echo "✅ Тестовая программа также не имеет утечек памяти"
        else
          echo "❌ В тестовой программе обнаружены утечки памяти"
          exit 1
        fi

    - name: Test with different inputs
      run: |
        echo "📊 Тестирование с различными входными данными..."

        # Тест 1: Матрица 1x1
        echo -e "1\n1\n5\n10" | ./matrix_multiplier > output1.txt
        if grep -q "50" output1.txt; then
          echo "✅ Тест 1x1 пройден"
        else
          echo "❌ Тест 1x1 не пройден"
          exit 1
        fi

        # Тест 2: Матрица 3x2
        echo -e "3\n2\n1\n2\n3\n4\n5\n6\n2\n3\n4\n5\n6\n7" | ./matrix_multiplier > output2.txt
        if grep -q "2 6" output2.txt && grep -q "12 20" output2.txt && grep -q "30 42" output2.txt; then
          echo "✅ Тест 3x2 пройден"
        else
          echo "❌ Тест 3x2 не пройден"
          exit 1
        fi

    - name: Cleanup
      run: |
        echo "🧹 Очистка временных файлов..."
        rm -f matrix_multiplier test_program test_input.txt output.txt output1.txt output2.txt
        echo "✅ Очистка завершена"

    - name: Build status
      run: |
        echo "🎉 Сборка и тестирование завершены успешно!"
        echo "📊 Статистика:"
        echo "   - Компиляция: ✅ Успешно"
        echo "   - Unit-тесты: ✅ Успешно"
        echo "   - Интеграционные тесты: ✅ Успешно"
        echo "   - Проверка памяти: ✅ Успешно"
